"""Query variation generation for evidence-first multi-search research.

This module provides deterministic, bounded query variation generation to ensure
broad search discovery before entity resolution is finalized.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Set


# Default configuration
DEFAULT_MAX_QUERY_VARIATIONS = 8

# Context keywords for different entity types
CONTEXT_KEYWORDS: Dict[str, List[str]] = {
    "organization": [
        "official website",
        "report",
        "annual report",
        "licensing",
        "regulation",
        "government",
        "law",
    ],
    "regulator": [
        "regulator",
        "regulation",
        "authority",
        "licensing",
        "government",
        "law",
        "electricity",
        "energy",
        "petroleum",
    ],
    "power_pool": [
        "power pool",
        "electricity",
        "energy",
        "market",
        "cooperation",
        "members",
        "official website",
    ],
    "project": [
        "project",
        "development",
        "implementation",
        "status",
        "progress",
    ],
    "person": [
        "biography",
        "profile",
        "role",
        "position",
        "organization",
    ],
    "location": [
        "location",
        "address",
        "country",
        "region",
        "coordinates",
    ],
    "commodity": [
        "commodity",
        "market",
        "price",
        "production",
        "trade",
    ],
    "default": [
        "information",
        "details",
        "description",
        "overview",
        "history",
        "background",
    ],
}


@dataclass
class QueryVariationConfig:
    """Configuration for query variation generation."""
    max_variations: int = DEFAULT_MAX_QUERY_VARIATIONS
    context_keywords: Dict[str, List[str]] = field(default_factory=lambda: CONTEXT_KEYWORDS.copy())
    use_acronym: bool = True
    use_base_name: bool = True
    use_contextual: bool = True
    
    def __post_init__(self) -> None:
        if self.max_variations < 1:
            self.max_variations = 1


@dataclass
class QueryVariation:
    """A single query variation with its origin."""
    query: str
    origin: str  # e.g., "base", "acronym", "contextual", "alias"
    weight: float = 1.0  # Priority/weight (0-1)


class QueryVariationGenerator:
    """Generate deterministic, bounded query variations for entity research.
    
    This generator ensures:
    1. Query variations are generated by code, not randomly by LLM
    2. Variations are bounded to prevent uncontrolled query explosion
    3. Variations are deterministic (same input = same output)
    4. Acronyms and aliases are properly extracted and used
    
    Example:
        >>> generator = QueryVariationGenerator()
        >>> variations = generator.generate("Zimbabwe Energy Regulatory Authority (ZERA)")
        >>> # Returns: ["Zimbabwe Energy Regulatory Authority", "ZERA", ...]
    """

    def __init__(self, config: Optional[QueryVariationConfig] = None):
        """Initialize query variation generator.
        
        Args:
            config: Optional configuration for variation generation
        """
        self.config = config or QueryVariationConfig()

    def generate(
        self,
        entity_name: str,
        entity_type: Optional[str] = None,
        context: Optional[Dict[str, Any]] = None,
        aliases: Optional[List[str]] = None,
        country: Optional[str] = None,
    ) -> List[QueryVariation]:
        """Generate query variations for an entity.
        
        Args:
            entity_name: The entity name to generate variations for
            entity_type: Optional entity type for context keyword selection
            context: Optional additional context (e.g., {"country": "Zimbabwe"})
            aliases: Optional list of known aliases
            country: Optional country for location-based variations
            
        Returns:
            List of QueryVariation objects, bounded by config.max_variations
        """
        cleaned_name = (entity_name or "").strip()
        if not cleaned_name:
            return []

        variations: List[QueryVariation] = []
        seen: Set[str] = set()
        
        # Extract components
        base_name = self._remove_acronym(cleaned_name)
        acronym = self._extract_acronym(cleaned_name)
        
        # Get context keywords
        context_keywords = self._get_context_keywords(entity_type, context)
        
        # Get aliases
        alias_list = aliases or []
        if context and isinstance(context, dict):
            alias_list = list(set(alias_list + context.get("aliases", [])))
        
        # Priority 1: Original entity name (highest weight)
        if cleaned_name not in seen:
            seen.add(cleaned_name)
            variations.append(QueryVariation(
                query=cleaned_name,
                origin="base",
                weight=1.0,
            ))
        
        # Priority 2: Base name without acronym (high weight)
        if base_name and base_name != cleaned_name and base_name not in seen:
            seen.add(base_name)
            variations.append(QueryVariation(
                query=base_name,
                origin="base_name",
                weight=0.95,
            ))
        
        # Priority 3: Acronym alone (high weight)
        if acronym and self.config.use_acronym and acronym not in seen:
            seen.add(acronym)
            variations.append(QueryVariation(
                query=acronym,
                origin="acronym",
                weight=0.9,
            ))
        
        # Priority 4: Acronym with country (if provided)
        if acronym and country and self.config.use_acronym:
            combined = f"{acronym} {country}"
            if combined not in seen:
                seen.add(combined)
                variations.append(QueryVariation(
                    query=combined,
                    origin="acronym_country",
                    weight=0.85,
                ))
        
        # Priority 5: Base name with country (if provided)
        if base_name and country:
            combined = f"{base_name} {country}"
            if combined not in seen:
                seen.add(combined)
                variations.append(QueryVariation(
                    query=combined,
                    origin="base_country",
                    weight=0.8,
                ))
        
        # Priority 6: Aliases
        for alias in alias_list:
            cleaned_alias = (alias or "").strip()
            if cleaned_alias and cleaned_alias not in seen:
                seen.add(cleaned_alias)
                variations.append(QueryVariation(
                    query=cleaned_alias,
                    origin="alias",
                    weight=0.75,
                ))
        
        # Priority 7: Contextual variations with base name
        if self.config.use_contextual:
            for keyword in context_keywords[:3]:
                # Base name + keyword
                if base_name:
                    combined = f"{base_name} {keyword}"
                    if combined not in seen:
                        seen.add(combined)
                        variations.append(QueryVariation(
                            query=combined,
                            origin="contextual",
                            weight=0.7,
                        ))
                
                # Acronym + keyword (if acronym exists)
                if acronym and self.config.use_acronym:
                    combined = f"{acronym} {keyword}"
                    if combined not in seen:
                        seen.add(combined)
                        variations.append(QueryVariation(
                            query=combined,
                            origin="contextual",
                            weight=0.65,
                        ))
        
        # Priority 8: Country-specific patterns
        if country:
            country_patterns = [
                f"{base_name} regulator {country}" if base_name else None,
                f"{base_name} government {country}" if base_name else None,
                f"{base_name} energy {country}" if base_name else None,
                f"{acronym} regulator {country}" if acronym and self.config.use_acronym else None,
                f"{acronym} government {country}" if acronym and self.config.use_acronym else None,
                f"{acronym} energy {country}" if acronym and self.config.use_acronym else None,
            ]
            
            for pattern in country_patterns:
                if pattern and pattern not in seen:
                    seen.add(pattern)
                    variations.append(QueryVariation(
                        query=pattern,
                        origin="country_specific",
                        weight=0.6,
                    ))
        
        # Sort by weight (descending) and deduplicate
        variations = self._sort_and_deduplicate(variations)
        
        # Apply max variations limit
        return variations[:self.config.max_variations]

    def _sort_and_deduplicate(
        self,
        variations: List[QueryVariation],
    ) -> List[QueryVariation]:
        """Sort variations by weight and deduplicate."""
        # Sort by weight descending
        variations.sort(key=lambda v: v.weight, reverse=True)
        
        # Deduplicate by query (case-insensitive)
        seen: Set[str] = set()
        deduped: List[QueryVariation] = []
        
        for variation in variations:
            query_lower = variation.query.lower().strip()
            if query_lower not in seen:
                seen.add(query_lower)
                deduped.append(variation)
        
        return deduped

    def _get_context_keywords(
        self,
        entity_type: Optional[str],
        context: Optional[Dict[str, Any]],
    ) -> List[str]:
        """Get context keywords based on entity type and context."""
        # Check context dict first
        if context and isinstance(context, dict):
            keywords = context.get("keywords", [])
            if isinstance(keywords, list):
                return keywords[:5]  # Limit to 5 keywords
        
        # Use entity type to select keywords
        if entity_type:
            type_lower = entity_type.lower()
            for type_key, keywords in self.config.context_keywords.items():
                if type_key.lower() in type_lower:
                    return keywords[:5]
        
        # Default keywords
        return self.config.context_keywords.get("default", [])[:5]

    @staticmethod
    def _extract_acronym(name: str) -> Optional[str]:
        """Extract acronym from parentheses at end of name.
        
        Examples:
            "Zimbabwe Energy Regulatory Authority (ZERA)" -> "ZERA"
            "Southern African Power Pool (SAPP)" -> "SAPP"
        """
        match = re.search(r"\s*\(([A-Z]{2,10})\s*$", name.strip())
        if match:
            return match.group(1).strip()
        
        # Also check for acronym at the beginning
        match = re.search(r"^\s*([A-Z]{2,10})\s*", name.strip())
        if match:
            acronym = match.group(1).strip()
            # Only return if it's not the entire name
            if len(acronym) < len(name.strip()):
                return acronym
        
        return None

    @staticmethod
    def _remove_acronym(name: str) -> str:
        """Remove acronym in parentheses from end of name.
        
        Examples:
            "Zimbabwe Energy Regulatory Authority (ZERA)" -> "Zimbabwe Energy Regulatory Authority"
        """
        return re.sub(r"\s*\([^)]+\)\s*$", "", name.strip())

    @staticmethod
    def extract_all_acronyms(text: str) -> List[str]:
        """Extract all acronyms from text (2-10 uppercase letters)."""
        return re.findall(r"\b([A-Z]{2,10})\b", text)


# Module-level convenience function
def generate_query_variations(
    entity_name: str,
    entity_type: Optional[str] = None,
    context: Optional[Dict[str, Any]] = None,
    max_variations: int = DEFAULT_MAX_QUERY_VARIATIONS,
) -> List[str]:
    """Generate query variations as a simple list of strings.
    
    This is a convenience function for code that just needs the query strings.
    
    Args:
        entity_name: The entity name
        entity_type: Optional entity type
        context: Optional context dict
        max_variations: Maximum number of variations to return
        
    Returns:
        List of query strings
    """
    generator = QueryVariationGenerator(
        QueryVariationConfig(max_variations=max_variations)
    )
    variations = generator.generate(
        entity_name,
        entity_type=entity_type,
        context=context,
    )
    return [v.query for v in variations]
